/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view;

import controller.CommunicationController;
import domain.Korisnik;
import domain.Ponuda;
import domain.Porudzbina;
import domain.StavkaPorudzbine;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import ui.view.components.TableModelPonuda;
import ui.view.components.TableModelPonudaKorisnik;
import ui.view.components.TableModelPorudzbina;

/**
 *
 * @author Luka
 */
public class FrmMainCustomer extends javax.swing.JFrame {

    private Korisnik korisnik;
    /**
     * Creates new form FrmMainCustomer
     */
    public FrmMainCustomer(Korisnik korisnik) {
        this.korisnik = korisnik;
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPorudzbine = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnNewOrder = new javax.swing.JButton();
        btnCancelOrder = new javax.swing.JButton();
        btnChangeOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPorudzbine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPorudzbine);

        btnView.setText("Detaljnije");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnNewOrder.setText("Nova porudzbina");
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderActionPerformed(evt);
            }
        });

        btnCancelOrder.setText("Otkazi porudzbinu");
        btnCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrderActionPerformed(evt);
            }
        });

        btnChangeOrder.setText("Promena porudzbine");
        btnChangeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChangeOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChangeOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNewOrder)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        try{
            TableModelPorudzbina model = (TableModelPorudzbina) tblPorudzbine.getModel();
            FrmViewOrder frm = new FrmViewOrder(model.getPorudzbinatAt(tblPorudzbine.getSelectedRow()));
            frm.setVisible(true);
            for(StavkaPorudzbine s : model.getPorudzbinatAt(tblPorudzbine.getSelectedRow()).getStavkePorudzbine()){
                System.out.println(s.getStavkaPorudzbineID());
                System.out.println(s.getStavkaPorudzbineNaziv());
                System.out.println(s.getCena());
                System.out.println("---------");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Morate izabrati porudzbinu koju zelite da pogledate!", "Neuspesan pregled", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderActionPerformed
        try{

            TableModelPorudzbina model = (TableModelPorudzbina) tblPorudzbine.getModel();
            Porudzbina p = new Porudzbina();
            FrmNewOrder frm = new FrmNewOrder(p, this.korisnik, model);
            frm.setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Sistem ne moze da kreira novu porudzbinu!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNewOrderActionPerformed

    private void btnCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrderActionPerformed
        try{
            int dialogOption = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da otkazete porudzbinu?");
            TableModelPorudzbina p = (TableModelPorudzbina) tblPorudzbine.getModel();
            Porudzbina porudzbina = p.getPorudzbinatAt(tblPorudzbine.getSelectedRow());
            if(dialogOption == JOptionPane.YES_OPTION){
                p.removeOrder(tblPorudzbine.getSelectedRow());
                CommunicationController.getInstance().deleteOrder(porudzbina);
                System.out.println(porudzbina.getPorudzbinaID());
                JOptionPane.showMessageDialog(this, "Uspesna otkazana porudzbina!", "Uspesno otkazivanje", JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Morate izabrati porudzbinu koju zelite da otkazete!", "Neuspesno otkazivanje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCancelOrderActionPerformed

    private void btnChangeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeOrderActionPerformed
        try{
            TableModelPorudzbina model = (TableModelPorudzbina) tblPorudzbine.getModel();
            
            Porudzbina p = model.getPorudzbinatAt(tblPorudzbine.getSelectedRow());
            FrmChangeOrder frm = new FrmChangeOrder(p, korisnik, model);
            frm.setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Morate izabrati porudzbinu koju zelite da promenite!", "Neuspesna promena", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnChangeOrderActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnChangeOrder;
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPorudzbine;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        System.out.println(korisnik.getNazivKorisnika());
        System.out.println(korisnik.getPasswordKorisnika());
        System.out.println(korisnik.getTipKorisnikaID().getTipKorisnikaNaziv());
        this.setTitle(korisnik.getNazivKorisnika());
        this.setLocationRelativeTo(null);
        this.setTitle("Glavni meni musterija");
        fillPorudzbine();
    }
    
    private void fillPorudzbine(){
        try{
            List<Porudzbina> porudzbineSve = CommunicationController.getInstance().getAllOrders();
            System.out.println(porudzbineSve.size());
            List<Porudzbina> porudzbine = new ArrayList<>();
            for(Porudzbina p : porudzbineSve){
                if(p.getKorisnikC().getId() == korisnik.getId()){
                    porudzbine.add(p);
                }
            }
            TableModelPorudzbina model = new TableModelPorudzbina(porudzbine);
            tblPorudzbine.setModel(model);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
}
