/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view;

import controller.CommunicationController;
import domain.Korisnik;
import domain.Ponuda;
import domain.Porudzbina;
import domain.StavkaPonude;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ui.view.components.TableModelPonuda;
import ui.view.components.TableModelPorudzbina;
import ui.view.components.TableModelPorudzbinaRestoran;
import ui.view.components.TableModelStavkaPonude;

/**
 *
 * @author Luka
 */
public class FrmMainRestaurant extends javax.swing.JFrame {

    private Korisnik korisnik;
    //private List<Ponuda> ponude;
    /**
     * Creates new form FrmMainRestaurant
     */
    public FrmMainRestaurant(Korisnik korisnik) {
        this.korisnik = korisnik;
        //this.ponude = new ArrayList<>();
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPonuda = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAddOffer = new javax.swing.JButton();
        btnDeleteOffer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPorudzbine = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnOdobri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPonuda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPonuda);

        jLabel1.setText("Ponude:");

        btnAddOffer.setText("Dodaj ponudu");
        btnAddOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOfferActionPerformed(evt);
            }
        });

        btnDeleteOffer.setText("Obrisi");
        btnDeleteOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOfferActionPerformed(evt);
            }
        });

        tblPorudzbine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPorudzbine);

        jLabel2.setText("Porudzbine:");

        jButton1.setText("Osvezi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnOdobri.setText("Odobri");
        btnOdobri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdobriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddOffer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteOffer, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(btnOdobri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddOffer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteOffer)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOdobri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOfferActionPerformed
        try{
        TableModelPonuda model = (TableModelPonuda) tblPonuda.getModel();
        Ponuda p = new Ponuda();
        FrmOfferAdd frm = new FrmOfferAdd(p, this.korisnik, model);
        frm.setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Sistem ne moze da kreira novu ponudu!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddOfferActionPerformed

    private void btnDeleteOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOfferActionPerformed
        try{
            TableModelPonuda p = (TableModelPonuda) tblPonuda.getModel();
            Ponuda ponuda = p.getPonudatAt(tblPonuda.getSelectedRow());
            p.removeOffer(tblPonuda.getSelectedRow());
            CommunicationController.getInstance().deleteOffer(ponuda);
            System.out.println(ponuda.getPonudaID());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Morate izabrati ponudu koju zelite da obrisete!", "Neuspesno brisanje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteOfferActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fillPorudzbine();
        JOptionPane.showMessageDialog(this, "Sistem je pronasao porudzbine", "Porudzbine", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnOdobriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdobriActionPerformed
        try{
            TableModelPorudzbinaRestoran model = (TableModelPorudzbinaRestoran) tblPorudzbine.getModel();
            Porudzbina p = model.getPorudzbinatAt(tblPorudzbine.getSelectedRow());
            p.setStatus(true);
            CommunicationController.getInstance().updateOrder(p);
            JOptionPane.showMessageDialog(this, "Uspesno odobrena porudzbina", "Odobrena porudzbina", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Morate izabrati porudzbinu koju zelite da odobrite!", "Neuspesno odobravanje", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnOdobriActionPerformed

    private void prepareView() {
        this.setTitle(korisnik.getNazivKorisnika());
        this.setLocationRelativeTo(null);
        this.setTitle("Glavni meni restoran");
        fillPonude();
        fillPorudzbine();
        
    }
    
    private void fillPonude(){
        try{
            List<Ponuda> ponudeSve = CommunicationController.getInstance().getAllOffers(korisnik);
//            List<Ponuda> ponude = new ArrayList<>();
//            for(Ponuda p : ponudeSve){
//                System.out.println("3");
//                if(p.getKorisnikID().getId() == korisnik.getId()){
//                    ponude.add(p);
//                }
//            }
            TableModelPonuda model = new TableModelPonuda(ponudeSve);
            tblPonuda.setModel(model);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void fillPorudzbine(){
        try{
            List<Porudzbina> porudzbineSve = CommunicationController.getInstance().getAllOrders();
            List<Porudzbina> porudzbine = new ArrayList<>();
            for(Porudzbina p : porudzbineSve){
                if(p.getKorisnikR().getId() == korisnik.getId()){
                    porudzbine.add(p);
                }
            }
            TableModelPorudzbinaRestoran model = new TableModelPorudzbinaRestoran(porudzbine);
            tblPorudzbine.setModel(model);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Sistem ne moze da pronadje porudzbine", "Neuspesno", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOffer;
    private javax.swing.JButton btnDeleteOffer;
    private javax.swing.JButton btnOdobri;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPonuda;
    private javax.swing.JTable tblPorudzbine;
    // End of variables declaration//GEN-END:variables
}
