/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view;

import controller.CommunicationController;
import domain.Artikl;
import domain.Korisnik;
import domain.Ponuda;
import domain.StavkaPonude;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ui.view.components.TableModelArtikl;
import ui.view.components.TableModelPonuda;
import ui.view.components.TableModelStavkaPonude;

/**
 *
 * @author Luka
 */
public class FrmOfferAdd extends javax.swing.JFrame {

    private Ponuda ponuda;
    private Korisnik korisnik;
    private TableModelPonuda model;
    /**
     * Creates new form FrmOfferAdd
     */
    public FrmOfferAdd(Ponuda ponuda, Korisnik korisnik, TableModelPonuda model) {
        this.ponuda = ponuda;
        this.korisnik = korisnik;
        this.model = model;
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblArtikli = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtOfferName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtStavkaNaziv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCenaStavke = new javax.swing.JTextField();
        btnDodajStavku = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        btnSacuvajPonudu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        tblArtikli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblArtikli);

        jLabel1.setText("Naziv:");

        jLabel2.setText("Naziv:");

        jLabel3.setText("Cena:");

        btnDodajStavku.setText("Dodaj stavku");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnObrisiStavku.setText("Obrisi stavku");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        btnSacuvajPonudu.setText("Sacuvaj ponudu");
        btnSacuvajPonudu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajPonuduActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOfferName, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtStavkaNaziv)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addComponent(txtCenaStavke))
                    .addComponent(btnDodajStavku)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnSacuvajPonudu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addComponent(btnObrisiStavku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtOfferName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSacuvajPonudu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStavkaNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCenaStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDodajStavku))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(btnObrisiStavku))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        try {
            TableModelStavkaPonude model = (TableModelStavkaPonude)tblStavke.getModel();
            TableModelArtikl model2 = (TableModelArtikl)tblArtikli.getModel();
            int selectedRow = tblArtikli.getSelectedRow();
            if(selectedRow == -1){
                throw new Exception("Izaberite artikl!");
            }
            if(txtStavkaNaziv.getText().length() < 1){
                throw new Exception("Unesite naziv stavke!");
            }
            if(Double.parseDouble(txtCenaStavke.getText()) <= 0){
                throw new Exception("Cena mora biti veca od 0!");
            }
                 Artikl artikl = model2.getArtiklAt(selectedRow);
                 double cena = Double.parseDouble(txtCenaStavke.getText());
                 String naziv = txtStavkaNaziv.getText();
                 StavkaPonude stavka = new StavkaPonude();
                 stavka.setArtikl(artikl);
                 stavka.setStavkaPonudeNaziv(naziv);
                 stavka.setCena(cena);
                model.addOfferItemNew(stavka);
        } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Unos nove ponude", JOptionPane.ERROR_MESSAGE);
         }
        
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed
        try{
            TableModelStavkaPonude s = (TableModelStavkaPonude) tblStavke.getModel();
            
            s.removeOfferItem(tblStavke.getSelectedRow());
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void btnSacuvajPonuduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajPonuduActionPerformed
        try{
            TableModelStavkaPonude modelS = (TableModelStavkaPonude) tblStavke.getModel();
            Ponuda p = modelS.getPonuda();
            p.setPonudaNaziv(txtOfferName.getText());
            p.setKorisnikID(korisnik);
            for(StavkaPonude s : p.getStavkePonude()){
                p.setPonudaCena(p.getPonudaCena() + s.getCena());
            }
            p = CommunicationController.getInstance().saveOffer(p);
            model.insertPonuda(p);
            model.fireTableDataChanged();
            JOptionPane.showMessageDialog(this, "Uspesna kreirana ponuda!", "Uspesna ponuda", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Unos nove ponude", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnSacuvajPonuduActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnSacuvajPonudu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblArtikli;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtCenaStavke;
    private javax.swing.JTextField txtOfferName;
    private javax.swing.JTextField txtStavkaNaziv;
    // End of variables declaration//GEN-END:variables

    
    private void prepareView(){
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("Nova ponuda");
        TableModelStavkaPonude model = new TableModelStavkaPonude(ponuda);
        tblStavke.setModel(model);
        try{
            List<Artikl> arikli = CommunicationController.getInstance().getAllArticles();
            TableModelArtikl model2 = new TableModelArtikl(arikli);
            tblArtikli.setModel(model2);
        }
        catch(Exception e){
            
        }
    }
    
}
